### ISSUE TITLE
Session key error

### ISSUE THREAD

**Issue by kristbaum** [arthist-lmu/artigo#188]
```
[pid: 21|app: 0|req: 162/162] 141.84.155.42 () {60 vars in 912 bytes} [Thu Nov 10 08:49:36 2022] OPTIONS /session/?id=490494 => generated 0 bytes in 2 msecs (HTTP/1.1 200) 8 headers in 426 bytes (1 switches on core 0)
[2022-11-10T08:49:41][ERROR] Internal Server Error: /session/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/api/src/artigo_api/frontend/views/session.py", line 64, in get
    session[str(tagging['resource_id'])].update(tagging)
KeyError: '39617'
```

**Comment by stefanieschneider** [comment]
This is always due to the search container being empty; cf. [#c39413b](https://github.com/arthist-lmu/artigo/commit/c39413bf76a9af8db12cd16d1ba5242635376712).
